---
title: Lorem Ipsum - Web Developer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: A blog about lorem ipsum ...
baseurl: "/space-jekyll-template"
url: http://victorvoid.github.io/space-jekyll-template/
username: lorem ipsum
user_title: Lorem Ipsum - FrontEnd
email: lorem.lorem@ipsum.com
twitter_username: loremipsum
github_username: loremipsum
discord_invite: cj5rg
linkedin_public_url: loremipsum
disqus_username: loremipsum
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png
markdown: kramdown
highlighter: rouge
permalink: "/:title/"
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false
links:
  section_1:
  - title: home
    url: "/"
    key_trigger: 1
  - title: my posts
    url: "/posts"
    key_trigger: 2
  - title: series
    url: "/series"
    key_trigger: 3
  - title: tags
    url: "/tags"
    key_trigger: 4
  - title: about me
    url: "/about"
    key_trigger: 5
  section_2:
  - title: github
    url: http://www.github.com/victorvoid
    new_tab: true
    key_trigger: g
  - title: twitter
    url: http://www.twitter.com/victorvoid
    key_trigger: t
  - title: search
    url: ''
    key_trigger: s
projects:
- name: fluany
  url: https://github.com/fluany/fluany
- name: vim-frontend
  url: https://github.com/victorvoid/vim-frontend
- name: generator-capybara
  url: https://github.com/victorvoid/generator-capybara
exclude:
- package.json
- src
- node_modules
